# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/hangfire

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# Don't edit manually! Use `build.bat version` command instead!
version: 1.7.0-build-0{build}

os: Visual Studio 2015

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  BuildEnvironment: appveyor
  Hangfire_SqlServer_ConnectionStringTemplate: Server=.\SQL2008R2SP2;Database={0};User Id=sa;Password=Password12!
  COVERALLS_REPO_TOKEN: 
    secure: oE4uB475V9hPzKmm+ZRP+1BacnMFOE98a/2tVeFieYJi5BbYG6X3VM+p6vKIQZdd
  COVERITY_TOKEN:
    secure: r3yBqxgALySnCK9W6uiStqoadsqYtrWQolzxGDVKF74=
  COVERITY_EMAIL:
    secure: wf51HXCiUYxuTe+eo3uQOxqyptSLrH4IEqq0958Rmx8=

# enable service required for tests
services:
  - mssql2008r2sp2
  - msmq

# branches to build
branches:
  # whitelist
  only:
    - master
    - dev

pull_requests:
  do_not_increment_build_number: true

shallow_clone: true

cache:
  - packages

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script:
  - choco install "sonarscanner-msbuild-net46" -y
  - choco install "sonarscanner-msbuild-netcoreapp2.0" -y
  - SonarScanner.MSBuild.exe begin /k:"HangFireFork" /d:sonar.organization="aleixlopezcarglass-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="4e0a76ecad19028340d48e2d603b9208eef8e4de"
  - build.bat ci
  - SonarScanner.MSBuild.exe end /d:sonar.organization="aleixlopezcarglass-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="4e0a76ecad19028340d48e2d603b9208eef8e4de"

after_build:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f coverage.xml

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\**\*.nupkg'
  - path: 'build\**\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

